### ISSUE TITLE
Disentangling `kineticLaws` of reversible reactions

### ISSUE THREAD

**Issue by paulflang** [sbmlteam/libsbml#144]
When an SBML reaction is reversible, it still only contains a single kineticLaw. Is there a function in libSBML that separates the single kineticLaw into a forward and reverse kineticLaw?

**Comment by fbergmann** [comment]
indeed, if the rate of the reaction is positive, the reaction would go into the forward direction, if it is negative in the backwards direction. There is no function in libSBML that would split them up. Though you could to so manually, replacing the reaction with 2 reaction (where the 2nd one would swap substrates and products) and change the rate to: `max(<rate>, 0)` for the forward direction, and `abs(min(0, <rate>))` for the reverse.

**Comment by paulflang** [comment]
Thanks! That'll do if the network shall be simulated with ODEs.

But if we want to do SSA, I think we would see less stochasticity than there actually is if we do it that way. I mean strictly speaking SSA requires mass action kinetics, in which case splitting is straightforward. But I could imagine some modellers would also want to use SSA with more complicated kineticLaws. But perhaps we should not encourage/allow this.

**Comment by fbergmann** [comment]
I agree, there is a straightforward way to do this in SBML for the modeler, they can (and probably should) explicitly model the forward and reverse reaction, instead of just using the `reversible=true` attribute. Then the SSA algorithm will do the correct thing. 

I dont see what libSBML could provide that would work for all tools / usecases. I think these are application specific issues (such as for example in COPASI, for stochastic simulations we replace X^2 with (X)(X-1), also a thing that is needed, but not something to generally apply).

**Comment by paulflang** [comment]
Thanks, Frank! We decided to write a function that can separate some bidirectional kineticLaws and throws an error suggesting to modify the SBML file if this fails.
