### ISSUE TITLE
Python kernel dies when overwriting SBMLDocument and accessing model

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libsbml#254]
Not sure what is going on, but the following results in a dying python kernel probably due to segmentation faults.
Somehow the model should be None. I.e. if the Document is overwritten the model should be cleaned up.

```python
import libsbml

doc: libsbml.SBMLDocument = libsbml.SBMLDocument(3, 1)
model: libsbml.Model = doc.createModel()

# this line results in a segmentation fault
doc: libsbml.SBMLDocument = libsbml.SBMLDocument(3, 1)

c: libsbml.Compartment = model.createCompartment()
```
**edit**: simplified example and clarified issue

**Comment by fbergmann** [comment]
the segfault actually happens when the model is accessed again, after the old document has been released, to be replaced by the new document. 

This is a known issue, and holds for all swig generated wrappers. I dont see what we could do about it. Since the whole model is stored on the SBMLdocument, when that one is deleted, all references to elements from it become invalid. the same thing will happen in C++ and all other languages.

**Comment by matthiaskoenig** [comment]
I figured this out. Thanks for the explanation. Nothing to do here, closing the issue.
